name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          source docker-settings.conf
          docker build . \
            --tag "$APP":"$TAG" \
            --tag "$APP":latest \
            ;

      - name: Get the release version
        id: pre-step
        shell: bash
        run: |
          release="${GITHUB_REF_NAME}"
          [[ "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && release="latest,$GITHUB_REF_NAME"
          [[ "${GITHUB_REF_NAME}" == "master" ]] && release=nightly
          printf "release-version=%s\n" "$release" >> "$GITHUB_OUTPUT"

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: pr1v/ansible-lint
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.pre-step.outputs.release-version }}"
